---
version: '3'

services:

  postgres:
    image: 'postgres:9.6'
    volumes:
      - './postgres:/docker-entrypoint-initdb.d'
    environment:
      POSTGRES_USER: 'atmo_app'
      POSTGRES_PASSWORD: 'atmosphere'
      POSTGRES_DB: 'atmo_prod'
      TROPO_DB_NAME: 'troposphere'

  atmosphere:
    image: 'cyverse/atmosphere:latest'
    command: '' # put your user id here if running locally
    volumes:
      - '../atmosphere:/opt/dev/atmosphere'
      - '../atmosphere-ansible:/opt/dev/atmosphere-ansible'
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
      - '/boot:/boot'
      - '/lib/modules:/lib/modules'
    depends_on:
      - 'postgres'

  troposphere:
    image: 'cyverse/troposphere:latest'
    command: '' # put your user id here if running locally
    volumes:
      - '../troposphere:/opt/dev/troposphere'
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
    depends_on:
      - 'atmosphere'
    ports:
      - '443:443'
      - '80:80'
