---
version: '3'

services:

  atmosphere:
    image: 'cyverse/atmosphere:latest'
    volumes:
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
      - '/boot:/boot'
      - '/lib/modules:/lib/modules'
    network_mode: 'host'

  troposphere:
    image: 'cyverse/troposphere:latest'
    volumes:
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
    depends_on:
      - 'atmosphere'
    ports:
      - '443:443'
      - '80:80'
    network_mode: 'host'
