---
version: '3'

services:

  atmosphere:
    image: 'cyverse/atmosphere:v36-5'
    volumes:
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
      - './logs/atmosphere:/opt/dev/atmosphere/logs'
      - './logs/celery:/var/log/celery'
      - '/boot:/boot'
      - '/lib/modules:/lib/modules'
    extra_hosts:
      - 'postgres:${dockerhost}'

  troposphere:
    image: 'cyverse/troposphere:v36-4'
    volumes:
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
      - './logs/troposphere:/opt/dev/troposphere/logs'
    depends_on:
      - 'atmosphere'
    ports:
      - '443:443'
      - '80:80'
    extra_hosts:
      - 'postgres:${dockerhost}'
