---
version: '3'

services:

  atmosphere:
    volumes:
      - 'guacamole-keys:/etc/guacamole/keys:rw'

  guacamole:
    image: 'guacamole/guacamole:0.9.14'
    environment:
      GUACAMOLE_HOME: '/guac_stuff'
      GUACD_HOSTNAME: 'guacd'
    volumes:
      - './guacamole:/guac_stuff:rw'
      - 'guacamole-keys:/guac_stuff/keys:rw'
    ports:
      - '8080:8080'

  guacd:
    image: 'guacamole/guacd:0.9.14'

volumes:
  guacamole-keys:
