---
version: '3'

services:

  atmosphere:
    image: 'cyverse/atmosphere:v36-2'
    volumes:
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
      - '/boot:/boot'
      - '/lib/modules:/lib/modules'
    extra_hosts:
      - 'postgres:${dockerhost}'

  troposphere:
    image: 'cyverse/troposphere:v36-2'
    volumes:
      - '../atmosphere-docker-secrets:/opt/dev/atmosphere-docker-secrets'
    depends_on:
      - 'atmosphere'
    ports:
      - '443:443'
      - '80:80'
    extra_hosts:
      - 'postgres:${dockerhost}'
